"""add user email_verified

Revision ID: 1a5c14d7c30c
Revises: 406a542ba5be
Create Date: 2025-07-18 15:11:23.405394

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a5c14d7c30c'
down_revision: Union[str, Sequence[str], None] = '406a542ba5be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Adiciona colunas nas tabelas existentes com server_default temporário
    op.add_column('delivery_partner',
                  sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('seller',
                  sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    op.alter_column('delivery_partner', 'email_verified', server_default=None)
    op.alter_column('seller', 'email_verified', server_default=None)

    # Corrige registros existentes na tabela shipment
    op.execute("""
            UPDATE shipment
            SET client_contact_email = 'no-reply@example.com'
            WHERE client_contact_email IS NULL
        """)

    # Agora pode aplicar NOT NULL com segurança
    op.alter_column('shipment', 'client_contact_email',
                    existing_type=sa.VARCHAR(),
                    nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipment', 'client_contact_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('seller', 'email_verified')
    op.drop_column('delivery_partner', 'email_verified')
    # ### end Alembic commands ###
