"""add client contact

Revision ID: 406a542ba5be
Revises: 987fcd8d7df5
Create Date: 2025-07-16 10:03:44.819066

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406a542ba5be'
down_revision: Union[str, Sequence[str], None] = '987fcd8d7df5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment', sa.Column('client_contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('shipment', sa.Column('client_contact_phone', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipment', 'client_contact_phone')
    op.drop_column('shipment', 'client_contact_email')
    # ### end Alembic commands ###
